### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by AndyMuc** [shibapm/Rocket#48]
Hello,

this project has no license information. A repo wide search for "copyright" also yielded no results. This most probably is just an oversight? Could you please add a license so everybody can use, share and modify the code? You might want to take a look at this page for more information: https://choosealicense.com/no-permission/

Thanks in advance,
Andy

**Comment by f-meloni** [comment]
Hey @AndyMuc
https://github.com/shibapm/Rocket/pull/49 should fix it :)
Thank you!
